#pragma once

bool isSADXLevel();
float GetDistance(NJS_VECTOR* orig, NJS_VECTOR* dest);
bool IsPointInsideSphere(NJS_VECTOR* center, NJS_VECTOR* pos, float radius);
ModelInfo* LoadMDL(const char* name, ModelFormat format);
AnimationFile* LoadAnim(const char* name);
void FreeMDL(ModelInfo* pointer);
void LoadAnimation(AnimationFile** info, const char* name, const HelperFunctions& helperFunctions);
void FreeAnim(AnimationFile* pointer);
void FreeLandTableObj();
void FreeLandTableInfo(LandTableInfo** info);
void LoadLandTable(const char* path, LandTableInfo** land, const TexPackInfo* tex);
void LoadLandManager_(LandTable* land);
void DeleteSetHandler();
void DeleteSETObjects();
void LoadLevelLayout(ObjectListHead* objlist, const char* s, const char* u);
void LoadLevelMusic(const char* name);
void SetStartEndPoints(const StartPosition* start, const LevelEndPosition* start2pIntro, const StartPosition* end, const LevelEndPosition* missionend);
void MovePlayersToStartPos(NJS_VECTOR pos, int yrot);
int IsPlayerInsideSphere(NJS_VECTOR* position, float a2);
signed int __cdecl GetPlayerRunningSpeed(unsigned __int8 a1, Float a2);
void ObjectSetupInput(EntityData1* twp, EntityData2* mwp);
NJS_OBJECT* DynCol_AddFromObject(ObjectMaster* obj, NJS_OBJECT* object, NJS_VECTOR* position, Angle rotY, int flags);
void __cdecl MainSubGlobalCol(ObjectMaster* obj);
void __cdecl MainSubGlobalDynCol(ObjectMaster* obj);
void KillPlayerFall(int a1);
void __cdecl EnemyBounceThing(unsigned __int8 playerID, float speedX, float speedY, float speedZ);
void __cdecl EnemyBounceThing_Wrapper(unsigned __int8 playerID, float a2, float a3, float a4);
void DoNextAction_r(int playerNum, char action, int unknown);
int __cdecl DoRotationStuff(unsigned __int8 a1, int a2, int a3, int a4);
void __cdecl StartPosManager(ObjectMaster* obj);;
ObjectMaster* __cdecl DoObjectThing(ObjectThing* things, ObjectMaster* parent);
ObjectMaster* __cdecl GetCharacterObject(unsigned __int8 character);